export const theme = {
	colors: {
		light: {
			profileContainerColor: '#fff',
			profileHeaderColor: '#000',
			dividerColor: '#000',
			sideBarColor: '#fff',
			sideBarLinkHoverColor: '#ddd',
			sideBarLinkActiveColor: '#ddd',
			sideBarRightBorderColor: '#000',
			bigSquaresBackgroundColor: '#CFCFCF',
			bigSquaresHoverColor: '#EDEDED',
			bigSquaresBorderColor: '#000',
			bigSquaresOrDividerColor: '#000',
			//
			accountBackgroundColor: '#ddd',
			basicInfoAccountImageBackgroundColor: '#111',
			basicInfoFileInputBackgroundColor: '#111',
			basicInfoFileInputTextColor: '#fff',
			accountSpanTextColor: '#000',
			accountInputBackgroundColor: '#111',
			accountInputTextColor: '#fff',
			basicInfoBioBackgroundColor: '#111',
			basicInfoBioTextColor: '#fff',
			//
			textColor: '#000',
			iconColor: '#000000',
			//
			buttonPrimaryColor: '#FCFCFC',
			buttonPrimaryColorDark: '#E6E6E6',
			//
			button0PrimaryColorHover: '#FFE822',
			button0PrimaryColorActive: '#FFE92A',
			//
			button1PrimaryColorHover: '#3088FF',
			button1PrimaryColorActive: '#2481FF',
			//
			button2PrimaryColorHover: '#FF2C3C',
			button2PrimaryColorActive: '#FF3939',
			//
			buttonPrimaryBorder: '#000',
			buttonFontColor: '#000',
			buttonIconColor: '#000',
			//
			notificationNavBarBackgroundColor: '#111',
			notificationNavBarTextColor: '#fff',
			notificationUlBackgroundColor: '#111',
			notificationUlTextColor: '#fff',
			notificationSvgColor: '#EEE',
			notificationLinkHoverColor: '#333',
			notificationLinkActiveColor: '#222',
			notificationOutletColor: '#222',
			//
			basicInfoButtonColor: '#FCFCFC',
			basicInfoButtonColorDark: '#FCFCFC',
			basicInfoButtonColorHover: '#3088FF',
			basicInfoButtonColorActive: '#2481FF`',
			basicInfoButtonBorderColor: '#000',
			basicInfoButtonFontColor: '#000',
			//
			contactInfoButtonColor: '#FCFCFC',
			contactInfoButtonColorDark: '#FCFCFC',
			contactInfoButtonColorHover: '#3088FF',
			contactInfoButtonColorActive: '#2481FF`',
			contactInfoButtonBorderColor: '#000',
			contactInfoButtonFontColor: '#000',
			//
			changePasswordButtonColor: '#FCFCFC',
			changePasswordButtonColorDark: '#FCFCFC',
			changePasswordButtonColorHover: '#3088FF',
			changePasswordButtonColorActive: '#2481FF`',
			changePasswordButtonBorderColor: '#000',
			changePasswordButtonFontColor: '#000',
			//
			deleteAccountButtonColor: '#FCFCFC',
			deleteAccountButtonColorDark: '#FCFCFC',
			deleteAccountButtonColorHover: '#FF2C3C',
			deleteAccountButtonColorActive: '#FF3939`',
			deleteAccountButtonBorderColor: '#000',
			deleteAccountButtonFontColor: '#000',
			//
		},
		dark: {
			profileContainerColor: '#000',
			profileHeaderColor: '#fff',
			dividerColor: '#fff',
			sideBarColor: '#000',
			sideBarLinkHoverColor: '#222',
			sideBarLinkActiveColor: '#222',
			sideBarRightBorderColor: '#fff',
			bigSquaresBackgroundColor: '#000',
			bigSquaresHoverColor: '#333',
			bigSquaresBorderColor: '#fff',
			bigSquaresOrDividerColor: '#fff',
			//
			accountBackgroundColor: '#222',
			basicInfoAccountImageBackgroundColor: '#eee',
			basicInfoFileInputBackgroundColor: '#eee',
			basicInfoFileInputTextColor: '#000',
			accountSpanTextColor: '#fff',
			accountInputBackgroundColor: '#eee',
			accountInputTextColor: '#000',
			basicInfoBioBackgroundColor: '#eee',
			basicInfoBioTextColor: '#000',
			//
			textColor: '#fff',
			iconColor: '#ffffff',
			//
			buttonPrimaryColor: '#000',
			buttonPrimaryColorDark: '#121212',
			//
			button0PrimaryColorHover: '#E7D800',
			button0PrimaryColorActive: '#E7D800',
			//
			button1PrimaryColorHover: '#0030D1',
			button1PrimaryColorActive: '#0030D1',
			//
			button2PrimaryColorHover: '#E00000',
			button2PrimaryColorActive: '#E00000',
			//
			buttonPrimaryBorder: '#fff',
			buttonFontColor: '#fff',
			buttonIconColor: '#fff',
			//
			notificationNavBarBackgroundColor: '#fff',
			notificationNavBarTextColor: '#000',
			notificationUlBackgroundColor: '#fff',
			notificationUlTextColor: '#000',
			notificationSvgColor: '#111',
			notificationLinkHoverColor: '#EEEEEE',
			notificationLinkActiveColor: '#EEEEEE',
			notificationOutletColor: '#eee',
			//
			basicInfoButtonColor: '#111',
			basicInfoButtonColorDark: '#111',
			basicInfoButtonColorHover: '#333',
			basicInfoButtonColorActive: '#222`',
			basicInfoButtonBorderColor: '#fff',
			basicInfoButtonFontColor: '#fff',
			//
			contactInfoButtonColor: '#111',
			contactInfoButtonColorDark: '#111',
			contactInfoButtonColorHover: '#333',
			contactInfoButtonColorActive: '#222`',
			contactInfoButtonBorderColor: '#fff',
			contactInfoButtonFontColor: '#fff',
			//
			changePasswordButtonColor: '#111',
			changePasswordButtonColorDark: '#111',
			changePasswordButtonColorHover: '#333',
			changePasswordButtonColorActive: '#222`',
			changePasswordButtonBorderColor: '#fff',
			changePasswordButtonFontColor: '#fff',
			//
			deleteAccountButtonColor: '#FCFCFC',
			deleteAccountButtonColorDark: '#FCFCFC',
			deleteAccountButtonColorHover: '#E00000',
			deleteAccountButtonColorActive: '#E00000`',
			deleteAccountButtonBorderColor: '#000',
			deleteAccountButtonFontColor: '#000',
			//
		},
	},
};
